# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/feedback_control',
                'doc_host': 'https://andreamunafo.github.io',
                'git_url': 'https://github.com/andreamunafo/feedback_control',
                'lib_path': 'feedback_control'},
  'syms': {'feedback_control.core': {'feedback_control.core.foo': ('core.html#foo', 'feedback_control/core.py')}}}
