# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_Intro_to_freq_response_and_bode_plots.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/06_Intro_to_freq_response_and_bode_plots.ipynb 5
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd

# import control
