# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/assignments/99_workspace.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/assignments/99_workspace.ipynb 6
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.animation as animation

from .simple_pendulum import *
from .dc_motor import *
